CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    publication_year INTEGER NOT NULL CHECK (publication_year >= 1450),
    author_id BIGINT NOT NULL REFERENCES authors(id)
);
CREATE INDEX idx_books_author ON books(author_id);
